### ISSUE TITLE
Implement the findings from the image alignment spike into the OCR pipeline

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#104]
Implement the findings from the image alignment spike into the OCR pipeline

**Acceptance Criteria**
Implement an `ImageAligner` class in the services module
Implement a `align` function that takes a `source_image`, `template_image`, and returns an `ndarray` aligned image.
Please include unit+integration tests

**Additional context**
Alignment Spike findings [[1](https://docs.google.com/document/d/12AibUgv1V7n3oiO5RQZxHE-PTrjKyHrsAQ6pVlar9i8/edit#heading=h.gltdn7lhpdmf)][[2](https://docs.google.com/presentation/d/1VL_DZuvh7Lintdacpbfe5Z8413t0u9G1TCR3pqxz-zA/edit)]

**Comment by bora-skylight** [comment]
@zdeveloper @jonchang Moving this to In Progress.
