### ISSUE TITLE
Explore AUTOSEGMENTATION tools to reduce manual template creation

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/IDWA#149]
Form segmentation and template creation takes up a considerable amount of time & manual effort. In line with our goal to reduce the amount of manual time and effort for users, we want to improve the current segmentation experience by exploring whether we can leverage a model to do part of that segmentation work. 

[Labelbox](https://labelbox.com/) is one tool that claims to be able to do autosegmentation and can serve as a starter point.

**Comment by bora-skylight** [comment]
Duplicate ticket: https://github.com/CDCgov/IDWA/issues/141

**Comment by knguyenrise8** [comment]
https://docs.google.com/document/d/1sUpGUU6qRRdLOJhP6FAhd1DIFhAhs4jMj3MG3PKvOoc/edit?usp=sharing
