### ISSUE TITLE
[DESIGN] User Experience for form segmentation & initial template creation

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/IDWA#150]
- Outline a few ways that the segmentation and initial template creation user flow could work
- Create initial prototype of experience of creating a form template

**Comment by bora-skylight** [comment]
2 workflows being explored:

- Creating a template on a first form
- Extracting data

**Comment by prikiser** [comment]
- New segmentation creation and editing labels (aspirational exploration)WIP [Figma Link](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/Smart-Segment?node-id=4-1689&t=OM3PwpnxMzTqKN4L-1)

**Comment by prikiser** [comment]
- Data extraction of existing segmentation template (aspirational) [Figma Screens](https://www.figma.com/proto/1FW8ZSDV90q2wpRPOADE9r/Smart-Segment?node-id=13-482&t=v8u2lda4USVST7pr-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=13%3A482&show-proto-sidebar=1)
- A combination of smart labels and manual ability

**Comment by prikiser** [comment]
- Manual label set up flow [Figma Screens](urhttps://www.figma.com/proto/1FW8ZSDV90q2wpRPOADE9r/Smart-Segment?node-id=63-1761&t=0zhfExhrUgIySGnB-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=63%3A1761&show-proto-sidebar=1l) 
- Screens will likely change, but overall, high-level concept.

**Comment by bora-skylight** [comment]
@prikiser I think we can call this ticket done since the initial user flows are complete, and we can create other tickets for updates being made. What do you think?

**Comment by prikiser** [comment]
> [@prikiser](https://github.com/prikiser) I think we can call this ticket done since the initial user flows are complete, and we can create other tickets for updates being made. What do you think?

@bora-skylight agree! I have some more minor tickets that I need to focus on adjusting based on tech constraints, the library, and such. Will connect with you on those.

**Comment by bora-skylight** [comment]
Closing this ticket then!
