### ISSUE TITLE
Explore Tools to Segment and Identify Coordinates in a PDF

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/IDWA#154]
Improve segmentation by exploring UI libraries to address the segmentation step.

Some helpful links:
https://github.com/TaqBostan/react-image-label
https://github.com/Kunduin/react-picture-annotation?tab=readme-ov-file
https://github.com/zxch3n/image-labeler-react

AC: 

Create a UI that segments a PDF based on custom boxes 
On Refresh we should store the segmentation and color and set a time on how long the data would persist

Evaluation Criteria for UI Library

Customizability
Maintainability
How easy/hard to save types
How easy/hard to save multiple labels
UI customization
How easy is it to persist the data
savable locations for each annotation

Question
What would be the input for the next step
What format does the data need to be in.

**Comment by knguyenrise8** [comment]
https://docs.google.com/document/d/1o7jnYF-08ewcZpZpQ8t8qQh7ZnzHTzDfJlKhFgfiERI/edit?usp=sharing
