### ISSUE TITLE
[V1] Annotation Page: Draw the boxes

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#167]
Build a page that will allow the user to annotate a pdf/image file from their local machine

for this story, we want to 
add the ability to draw boxes on the image when a label is selected

**Acceptance Criteria**

- clicking on Submit Button. 
  - will save in-progress template to the local storage
  - Will change the route to ```/new-template/save```
- follow the attached design, use uswds components without customization
- the route to this page should be ```/new-template/annotate```
- the back button should go to the route of ```/new-template/upload```
- the x button should be non functional

**Additional context**

disregard the label  search box ui
![Image](https://github.com/user-attachments/assets/87f8751c-d1ef-495b-bde0-278b4ffbbefb)

**Comment by bora-skylight** [comment]
Splitting this ticket into two with the addition of: https://github.com/CDCgov/IDWA/issues/190
