### ISSUE TITLE
UI JSON

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#174]
Update UI JSON design to incorporate more of a table variant and remove the raw data version.

Columns
1. Label
2. Value  
~~3. Include type (number, text, phone number, email, address (handle multiple)~~ [keeping off for now]

![Image](https://github.com/user-attachments/assets/899852e6-6baf-4e75-bb6a-be7278d9076c)

**Comment by prikiser** [comment]
@zdeveloper @knguyenrise8 I added an image attachment to the updated table design. Let me know if editing within the table becomes too complicated for V1. If so, I can create a design to edit in a modal (although inline is preferable).
