### ISSUE TITLE
[V1] Create the save template page

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#183]
Build a page that will allow the user to save the tempate on their browser local storage

**Acceptance Criteria**
- follow the attached design, use uswds components without customization
- the route to this page should be ```/new-template/save```
- the back button should route back to  ```/new-template/annotate```
- the x button should route to  ```/```
- the submit button should save the template to the browser local storage and then route to ```/```
- ignore the "add tags" and "asset type" fields on the linked designs for this story

**Additional context**
https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=108-3977&t=BK8Fi3dzPw4X4ZBl-4
![image](https://github.com/user-attachments/assets/d7499fff-d80c-4453-8536-de43b74c0197)

**Comment by knguyenrise8** [comment]
technically this happens in the previous step and sets everything there

**Comment by zdeveloper** [comment]
saved templates structure in local storage

"templates": [
    {
        "name": "template 1",
        "description":"quest lab",
        "images": [...],
        "fieldNames": [...]
    }
]

**Comment by zdeveloper** [comment]
Moving to DONE in our spring planning meeting.
