### ISSUE TITLE
[V1] Annotation Page: Initiate drawing a box after selecting a label

### ISSUE THREAD

**Issue by bora-skylight** [CDCgov/IDWA#190]
For this story, we want to connect the labels on the left hand size to the boxes being drawn on the image.

**Acceptance Criteria**
- clicking on a label enables you to draw a box for the label on the image with the same color highlighted, as in the design
- Allow for a labeled box to be deleted

**Design Artifacts**
- [Prototype](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=402-10277&t=d5pXEg1sVI9k7hI0-1) for resizing and delete 
    - Link to [figma](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=402-10441&t=d5pXEg1sVI9k7hI0-1) with notes 
- [Prototype](https://www.figma.com/proto/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=402-10277&t=O7dG9zb0RwTRipbY-1&scaling=min-zoom&content-scaling=fixed&page-id=402%3A9422&starting-point-node-id=402%3A10277&show-proto-sidebar=1) for clicking on label to activate creation of bounding box 
   Link to [figma](https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=402-10277&t=d5pXEg1sVI9k7hI0-1) with notes

![Image](https://github.com/user-attachments/assets/11ea340f-c77f-4651-aeaf-44877d45fe9d)

**Comment by bora-skylight** [comment]
@knguyenrise8 @zdeveloper @prikiser here is the story that I split out from Kevin's previous ticket.

@prikiser for the microinteractions of the box & labels, this story accounts for the following: 1) ability to delete a box and 2) choose a label & then allow for a box of the same color to be drawn.

@zdeveloper @arinkulshi should we assume that there should only be a 1:1 relationship between label and box? So a label should not be assigned to multiple boxes otherwise the data extraction will be confused?

**Comment by zdeveloper** [comment]
> @knguyenrise8 @zdeveloper @prikiser here is the story that I split out from Kevin's previous ticket.
> 
> @prikiser for the microinteractions of the box & labels, this story accounts for the following: 1) ability to delete a box and 2) choose a label & then allow for a box of the same color to be drawn.
> 
> @zdeveloper @arinkulshi should we assume that there should only be a 1:1 relationship between label and box? So a label should not be assigned to multiple boxes otherwise the data extraction will be confused?

Yes, that is a valid assumption, there is 1 box per label,  and 1 label per box

**Comment by knguyenrise8** [comment]
Look into way to override right click to go into active state

**Comment by knguyenrise8** [comment]
1 - 1 box to label vice versa label to box. subject to change

**Comment by arinkulshi-skylight** [comment]
@knguyenrise8  based on the review we do not have 1 box to 1 label as in the AC. We would need to address this to close the ticket.

**Comment by knguyenrise8** [comment]
add single click to get out of edit mode

**Comment by knguyenrise8** [comment]
add dynamic logic to remove not found
