### ISSUE TITLE
[V1] Extract: Build the Review page

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#197]
Build a page that will allow the user to review the output of the OCR

**Acceptance Criteria**

- show the key/value data returned from the OCR API in the table
- display the document on the right side
- show the confidence returned from the OCR API
- follow the attached design, use uswds components without customization
- the route to this page should be `/extract/review`
- the back button should go back to the  `/extract/upload`
- once the submit button is clicked, then route to `/extract/submit`
- the x button should route to `/`
- Dont worry about the overall confidence score in this story

**Additional context**
https://www.figma.com/design/1FW8ZSDV90q2wpRPOADE9r/MDE?node-id=562-4259&t=Ojs61BjqZVSBkZh8-4

**Comment by arinkulshi-skylight** [comment]
{
  "submission": {
    "template_name": "Invoice_Template_01",
    "template_image": "data:image/png;base64,....",  // Base64-encoded template image string
    "file_name": "invoice_123.png",
    "file_image": "data:image/png;base64,....",  // Base64-encoded file image string
    "results": {
      "nbs_patient_id": {
        "text": "SIENNA HAMPTON",
        "confidence": 98.75
      },
      "nbs_cas_id": {
        "text": "123555",
        "confidence": 95.42
      },
      "nbs_date_of_birth": {
        "text": "01/01/1990",
        "confidence": 97.10
      }
    }
  }
} Here is the updated json structure that will be read from this ticket
