### ISSUE TITLE
Request Skylight Azure access

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/IDWA#202]
Is your feature request related to a problem? Please describe.
We want to host IDWA MDE on Skylight's Azure

Additional context
Setup a meeting with the access team
Develop needed material to secure access

**Comment by bora-skylight** [comment]
@zdeveloper is this ticket done effectively or at least in review since we have the account now?

**Comment by zdeveloper** [comment]
Done, we have the creds to Slylight Azure
