### ISSUE TITLE
Optimize SCSS Build Pipeline

### ISSUE THREAD

**Issue by schreiaj** [CDCgov/IDWA#222]
Currently our SCSS builds happen on first load and take a non-trivial amount of time. This is due to how [we are importing USWDS](https://github.com/CDCgov/IDWA/blob/main/OCR/frontend/src/style/index.scss#L3) which is an approach they [recommend against](https://designsystem.digital.gov/components/packages/)

Removing this line and adding only the packages we use does significantly improve compilation times however hunting down all the packages we use and testing each page requires a bit of effort.

**Comment by bora-skylight** [comment]
@schreiaj @zdeveloper adding this to the sprint, correct? looks like it's already in progress

**Comment by schreiaj** [comment]
It's not a blocker, but the sooner we resolve it likely the less effort it will be.
