### ISSUE TITLE
Microsoft OCR model is now giving extremely bad results

### ISSUE THREAD

**Issue by jonchang** [CDCgov/IDWA#320]
**Describe the bug**

Microsoft OCR models are now giving very bad results (hallucinating) as seen in this gif from https://github.com/CDCgov/ReportVision/pull/316:

![Kapture 2024-10-11 at 13 48 24](https://github.com/user-attachments/assets/e083cf03-b8a9-4949-93a1-d2e6e35b757b)

**Impact**

We cannot rely on OCR pipelines

**To Reproduce**

1. Attempt to OCR this image using our pipeline: ![lab_template_crop](https://github.com/user-attachments/assets/1a0ff1a4-fb22-484c-8c36-d503fe0f4a3c)
2. Observe poor results: `MILKE, JOHORA, JOHORA, JOHORA, JOHORA, JOHORANANANAN` (confidence: 34.49%)

**Expected behavior**

Better results from the OCR 

**Additional context**

* Individual (not aggregate) confidence scores are extremely low when I dig into this code.
* resolution of the input does not seem to matter - I created a 'hires' version and the output becomes `MIKE INVOICE.COME FOR DETAILS. FREE SANDWICH!`
<img width="403" alt="lab_template_hires" src="https://github.com/user-attachments/assets/958fe813-6960-4352-9310-9804fc56cb64">

* tesseract has absolutely no problem with it
```console
% tesseract lab_template_crop.png -  
Estimating resolution as 109
Mike
```

**Comment by bora-skylight** [comment]
@jonchang Thank you for picking this up!

@jonchang @schreiaj can you all add what changes you would want to make in order to address this bug outside of investigation?

**Comment by schreiaj** [comment]
> @jonchang Thank you for picking this up!
> 
> @jonchang @schreiaj can you all add what changes you would want to make in order to address this bug outside of investigation?

Critical - we need to understand it, my proposed acceptance criteria for this ticket would be: 

- [ ] Able to reliably replicate hallucination of text 
- [ ] Document (~1 pager) underlying cause
- [ ] Propose at least a single solution to resolve this 

I'd also like to time box this investigation if possible, @jonchang do you think you can get the above things by Dev Sync on Friday?
