### ISSUE TITLE
Generate disease form dataset

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#4]
The goal of this ticket is to have a better disease form dataset for testing and evaluating our solution

**Acceptance Criteria**
Please utilize the PDF's already shared with us in the drive, for Pertussis, Hepatitis (A/B/Viral), and Mumps

Each form should have the following versions

- Empty form
- Scanned Handwritten form
- Scanned Computer filled 
- Empty fillable form
- Filled out fillable form

**Additional context**
[Texas case investigation forms](https://www.dshs.texas.gov/notifiable-conditions/investigation-forms)

Texas Notifiable Conditions
https://www.dshs.texas.gov/sites/default/files/IDCU/investigation/Reporting-forms/Notifiable-Conditions-2024Color.pdf

**Comment by derekadombek** [comment]
@zdeveloper Was the initial plan for this to manually fill out each of these forms with dummy data, using the different formatting of "typing" and "handwrittern" and then save it in a place the repo? If so how many of each were you thinking? I Imagine this is to provide different model training methods right?

**Comment by zdeveloper** [comment]
> @zdeveloper Was the initial plan for this to manually fill out each of these forms with dummy data, using the different formatting of "typing" and "handwritten" and then save them in the OCR dir for the code/tests to point to? If so how many of each were you thinking? Are we using these datasets for model training or unit testing purposes?

The idea was to have 5 forms 

1. Pertussis
2. Hepatitis (A)
3. Hepatitis (B)
4. Hepatitis (Viral)
5. Mumps

and for each form, we have the following versions

1. Empty form
2. Scanned Handwritten form
3. Scanned Computer filled
4. Empty fillable form
5. Filled out fillable form

I would say the use would be for both unit testing and model training (providing examples for the AI to learn from)

**Comment by derekadombek** [comment]
complete_fillable: https://drive.google.com/drive/folders/1cZHn5JM0V9RnVnIz2qZz_e8Nq9FDmJOe
scanned_complete_fillable: https://drive.google.com/drive/folders/15KyB8Lxz7Vun_3J2zoRuLDD4dLBX-vuc
scanned_complete_handwritten: https://drive.google.com/drive/folders/1Ss_vpv3f3NVv7Ja0jq-J5l4yGv8_gATh

Blanks: https://drive.google.com/drive/folders/118Npqkf5mW2sm8zd3ohQ9a7lDe7JDAIo & https://drive.google.com/drive/folders/1tEbH_xfCAPPf-mqk-YqC1hv9DXeU59FV
