### ISSUE TITLE
Connect tesseract OCR to front end API 

### ISSUE THREAD

**Issue by jonchang** [CDCgov/IDWA#414]
Follow up issue from https://github.com/CDCgov/ReportVision/pull/375#pullrequestreview-2449723810

**Comment by bora-skylight** [comment]
@jonchang can you explain how we should think about this ticket? 
If tesseract performs better than our current model, would this ticket be needed in order to make use of it? 
@arinkulshi @schreiaj at this point, do we even connect our front end directly to an OCR API?
