### ISSUE TITLE
SPIKE: Research RPA tools

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#43]
Research and evaluate RPA and RPA specific tools

Research the following tools
- UI Path
- Automation Anywhere
- Blue Prism
- OpenRPA
- Node-RED

**Acceptance Criteria**
Please write up a spike doc and save it to the drive and present the findings either in slack or as a techtalk in the dev sync meeting.

**Additional context**
consider the following criteria

- How good is the tool, accuracy
- Ease of use
- Ease of implementation for developer
- Integration (API access)
- Commercial or Opensource (preference for opensource)

**Comment by knguyenrise8** [comment]
[UI Path](https://docs.google.com/document/d/1Ar22o6RIRbJyzgUa7_TZTnz8BPdS9kvMtw8E_H7ZZ3M/edit?usp=sharing)

**Comment by derekadombek** [comment]
> [UI Path](https://docs.google.com/document/d/1Ar22o6RIRbJyzgUa7_TZTnz8BPdS9kvMtw8E_H7ZZ3M/edit?usp=sharing)

Were you able to get this working locally? I'm guessing you have a Macbook as well?

**Comment by knguyenrise8** [comment]
i had to use a vm lol
