### ISSUE TITLE
Build a segmentation template for a real disease form

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#65]
Please build a segmentation template for Hepatitis A, Acute Case Track Record in order to be able to run it thought OCR

**Acceptance Criteria**

- Build separate segmentation template for page 1 and 2
- Build labels.json
- Ignore checkboxes for this form

**Additional context**
https://drive.google.com/file/d/1egJe0k5yg8BVUadj-I3LZ-Lz34uLVDex/view?usp=sharing

**Comment by arinkulshi-skylight** [comment]
Segmentation Templates
https://drive.google.com/file/d/1Ea1b8XwkwIw8y41EM_pDZWAzoqj9rvu6/view?usp=sharing
https://drive.google.com/file/d/1MZ8fr8Jkr8NWXs0PfcGvEXsQ03m6Rpjj/view?usp=sharing

Labels Files
https://drive.google.com/file/d/1VMq6-0jcxLa_v_t8oxUL8U2_ATHf3e86/view?usp=sharing
https://drive.google.com/file/d/1xJ-WUULr6aTlOeVXM5HcYbFdhrbDZJwC/view?usp=sharing

**Comment by zdeveloper** [comment]
Hey @arinkulshi-skylight can you double check this template and the labels

1. we cant use black and white as labels
2. in `labels_hep_page1.json` the labels are repeated with different RGB values
![Image](https://github.com/CDCgov/IDWA/assets/4952042/ac662059-9eb0-4c23-9e37-38617bb4f48c)
3. the format of the labels is incorrect
