### ISSUE TITLE
Spike: Synthetic data creation

### ISSUE THREAD

**Issue by knguyenrise8** [CDCgov/IDWA#78]
Create a 1 pger/2 pger on how effective fine tuning llms on parsing pdfs. Provide numbers on time to parse a pdfs. create numbers on 1page, 2page, 3page etc, costs/tokens per transaction. 

Look into GPT 3.5/4 OLLAMA etc.

**Comment by bora-skylight** [comment]
@knguyenrise8 Can you please break down this ticket into 3 separate tickets as we mentioned above?
