### ISSUE TITLE
Integrate the output of OCR into NBS

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#95]
Integrate the output of OCR into NBS, by generating a PHDC document.

**Acceptance Criteria**
- Map the OCR key/value output into a PHDC input dataclass.
- Generate PHDC using the dibbs phdc library, feel free top copy over the code for right now [[link](https://github.com/CDCgov/phdi/tree/8a105ca7e2c495adec9db7a7c8516bbc247df669/containers/message-parser/app/phdc)]
- Integrate patient dataclass only

**Additional context**
https://github.com/CDCgov/phdi/tree/8a105ca7e2c495adec9db7a7c8516bbc247df669/containers/message-parser/app/phdc
https://github.com/CDCgov/phdi/blob/8a105ca7e2c495adec9db7a7c8516bbc247df669/containers/message-parser/app/phdc/models.py

**Comment by bora-skylight** [comment]
@arinkulshi-skylight @zdeveloper Is this actually in progress or do we want to deprioritize this and focus on the Digitize step for checkboxes? I would vote for working on this one step of the pipeline at a time. Please let me know!

**Comment by bora-skylight** [comment]
@zdeveloper @arinkulshi-skylight can we close this ticket?
