### ISSUE TITLE
Create segmentation template and labels file using PDF metadata

### ISSUE THREAD

**Issue by arinkulshi-skylight** [CDCgov/IDWA#96]
Automate creation of labels.json file and segment template by using xy coordinates extracted from PDF metadata

Acceptance Criteria
Script should take xy coordinates and generate semgmentation template using random RGB values 
Script should create labels.json file with key and appropriate RGB value.

Additional context
Example File: https://drive.google.com/file/d/1dF60uWSK9khlaxbRQ3nrXyDrojdWq4iJ/view?usp=sharing

**Comment by bora-skylight** [comment]
@arinkulshi-skylight @zdeveloper can we close this out? it's been weeks in review
