### ISSUE TITLE
Automatically move tickets to the new sprint

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/IDWA#98]
Currently, we have to move outstanding tickets manually to the next iteration.
this ticket will enable us to automatically move tickets to the new sprint.

We have weekly sprints that start on Thursday, and end on Wednesday.

**Acceptance Criteria**
potential solutions https://github.com/marketplace/actions/move-to-next-iteration

**Additional context**
reach out to Bora for more info about the problem.

**Comment by bora-skylight** [comment]
Update: automatically moving tickets to new sprint failed, will reprioritize this automation in the future

@derekadombek closing this for the time being
